import { stateType } from './type';

const initialState: stateType = {
  dreamCore: {
    core: {title: '', description: ''},
    side: [
      {title: '', description: ''},
      {title: '', description: ''},
      {title: '', description: ''},
      {title: '', description: ''},
      {title: '', description: ''},
      {title: '', description: ''},
      {title: '', description: ''},
      {title: '', description: ''},
    ]
  },
  dream0: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream1: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream2: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream3: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream4: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream5: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream6: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
  dream7: [
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
    {title: '', description: ''},
  ],
};

export default initialState;
