version: 2.1

jobs:
  unit_tests:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run: yarn
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: "test-reports/jest-junit.xml"
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: yarn build
 

workflows:
  version: 2
  test_build_app:
    jobs:
      - unit_tests
      - build