export const UPDATE_CORE_UNIT = 'UPDATE_CORE_UNIT';
export const UPDATE_CORE_SIDE_UNIT = 'UPDATE_CORE_SIDE_UNIT';
export const UPDATE_UNIT = 'UPDATE_UNIT';
export const UPDATE_CURRENT_UNIT = 'UPDATE_CURRENT_UNIT';
